In [3]:
import numpy as np
my_List=[1,2,3,4]
type(np.array(my_List))
arr=np.array(my_List)
arr

array([1, 2, 3, 4])

In [5]:
np.arange(0,10)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.random.randint(0,10)

3

In [27]:
np.random.seed(11)
np.random.randint(0,10,2)

array([9, 0])

In [53]:
np.random.seed(11)
arr=np.random.randint(0,10,9)
arr

array([9, 0, 1, 7, 1, 7, 2, 8, 0])

In [62]:
np.random.seed(11)
arr=np.random.randint(0,10,9)
arr.max()
arr.mean()
arr.argmax()
arr.argmin()
arr.reshape(3,3)

array([[9, 0, 1],
       [7, 1, 7],
       [2, 8, 0]])

In [64]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [68]:
mat[0,0]
mat[2,1]
mat[:,0]
mat[0,:]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])